# Site
repository: groverankur/groverankur
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ankur Grover
title: Data Engineer
email: grover.ankur@gmail.com
website: https://github.com/groverankur

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: grover_ankur
github_username:  groverankur
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ankur-grover
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: groverankur
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I'm a highly skilled enterprise/solution architect and data engineer with over 14 years of experience. With a passion for designing and implementing large distributed systems, technical consulting, project management, and technology implementation, I have a proven track record of delivering successful projects that drive business value.

  My technical expertise in Hadoop, Enterprise Information Management, Data Management, and Application integration, combined with my proficiency in data modeling, ETL, and data warehousing, has allowed me to design and build scalable data solutions that extract insights and drive innovation.

  But it's not just about the technical skills. I'm also a people person who enjoys working with cross-functional teams to deliver high-quality work that exceeds expectations. My excellent analytical, team-working, project-management, communication, and organizational skills enable me to manage multiple priorities in fast-paced environments while maintaining a positive attitude.

  When I'm not working on exciting data projects, you can find me <mark>exploring the outdoors</mark> or <mark>reading books</mark>. I believe that balance is key to a fulfilling life, both personally and professionally.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Jio Platforms Limited
        link: jio.com
        # link_text: boringcompany.com
        sub_title: Deputy General Manager - BI Analytics
        caption: May 2016 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            •	Implementation of Ingesting wide variety of data like structured, unstructured, and semi structured into the Big data eco systems with batch processing, real time streaming and SQL using big data pipeline, Hive jobs, PySpark jobs, Kafka on Jio Big Data Hadoop clusters.
            •	Handled different Hadoop Cluster with a current size of 300+ Nodes and 30 Petabytes capacity.
            •	Provide technical thought leadership on Big Data strategy, adoption, architecture, and design, as well as data engineering and modelling.
            •	Providing expert level guidance on Big Data best practices and standards.
            •	Work with product owners, business SME and data ingestion and reporting architects to identify requirements and consolidate enterprise data model consistent with business processes.
            •	Implementation of technical solution for backup and retrieval of historical data to and from Hadoop cluster.
            •	Developed and Implemented Data extraction and correlation between different data stream using PySpark. 
            •	Responsible of setting up team objectives, preparing weekly and monthly project review report to management, regular weekly status calls with team. 
            •	Application Operation Management for application related to Business Analytics and Regulatory team 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Punjab Technical University, Jalandhar
        caption: 2003 - 2007
        sub_title: Bachelor of Technology in Electronics & Communication
        quote: >
          The Punjab Technical University was established by an act of State Legislature on on 16th January, 1997, to promote technical, management and pharmaceutical education in the state at degree level and above
        description: | # this will include new lines to allow paragraphs
          During my degree at University I learnt lots of key skills such as team work and project management. Although we mainly focused on software development and the principles of programming I use a lot of these skills to my advantage in my day to day work.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
